name: huawei_new
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  image: ^4.1.3
  cached_network_image: ^3.3.0
  date_picker_plus: ^2.0.2
  date_format: ^2.0.7
  intl: ^0.19.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.2.0
  printing: ^5.11.1
  blue_thermal_printer: ^1.2.3
  bluetooth_print: ^4.3.0
  share: ^2.0.4




dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/default/huawei.png
    - images/default/

